import {
  ChangeDetectionStrategy,
  Component,
  computed,
  forwardRef,
  input,
  model,
  signal,
} from "@angular/core";
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from "@angular/forms";

/**
 * Design System — <mur-select>: a native select as a form control (CVA) with
 * PROJECTED options (static or @for-generated by the caller). Options paint
 * var(--surface-overlay) via the global primitives (rule T3).
 *
 * TWO ways to drive it, and they must not fight:
 *
 *   - `formControlName` / `[formControl]` / `[ngModel]` — the ControlValueAccessor
 *     path. Angular calls `writeValue` / `setDisabledState`.
 *   - `[(value)]` + `[disabled]` — the signal path, for callers with no reactive
 *     form (the onboarding wizard is signals-only).
 *
 * `value` is a `model()`, so `writeValue` and a caller's `[(value)]` write the
 * SAME signal — Angular's forms directive is just another writer, and every
 * change flows back out through `valueChange`. `disabled` cannot be a plain
 * input, because `setDisabledState` needs to WRITE it and an input signal is
 * read-only; the CVA's answer lives in its own private signal and the two
 * sources are OR-ed in {@link isDisabled} (either one disables — matching how
 * `<select [disabled]>` behaves under a disabled FormControl).
 */
@Component({
  selector: "mur-select",
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: "./select.component.html",
  styleUrl: "./select.component.scss",
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => MurSelectComponent),
      multi: true,
    },
  ],
})
export class MurSelectComponent implements ControlValueAccessor {
  readonly ariaLabel = input<string | null>(null);

  /** The selected option value. Two-way (`[(value)]`) AND the CVA's model. */
  readonly value = model("");

  /** Caller-driven disable. Independent of — and OR-ed with — `setDisabledState`. */
  readonly disabled = input(false);

  /** `setDisabledState` from a disabled FormControl. Private: the input is read-only. */
  private readonly cvaDisabled = signal(false);

  /** The effective disabled state the `<select>` binds. */
  readonly isDisabled = computed(() => this.disabled() || this.cvaDisabled());

  private onChange: (v: string) => void = () => undefined;
  private onTouched: () => void = () => undefined;

  writeValue(v: unknown): void {
    this.value.set(v == null ? "" : String(v));
  }
  registerOnChange(fn: (v: string) => void): void {
    this.onChange = fn;
  }
  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }
  setDisabledState(d: boolean): void {
    this.cvaDisabled.set(d);
  }

  onChangeEvent(e: Event): void {
    const v = (e.target as HTMLSelectElement).value;
    this.value.set(v);
    this.onChange(v);
    this.onTouched();
  }
}
