import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  input,
  output,
  signal,
  viewChild,
} from "@angular/core";
import type { GraphPayload } from "../../core/models";
import { MarkdownComponent } from "../../shared/markdown.component";
import { AssistantSourcesComponent } from "../../shared/assistant-sources.component";
import { MoveToMenuComponent } from "../folders/move-to-menu.component";
import { MeetingActionsComponent } from "./meeting-actions.component";
import { MeetingChatComponent } from "./meeting-chat.component";
import { MeetingRecipesComponent } from "./meeting-recipes.component";
import { RelatedMeetingsComponent } from "./related-meetings.component";

/** One checklist entry parsed from a `- [ ]` / `- [x]` action-item line. */
export interface ActionItemLine {
  done: boolean;
  text: string;
}

/** A parsed `## Heading` section of the note body. */
export interface NoteSection {
  heading: string;
  kind: "actions" | "bullets" | "prose";
  paragraphs: string[];
  bullets: string[];
  actions: ActionItemLine[];
}

/** The whole note, decomposed into front-matter + body sections. */
export interface ParsedNote {
  tags: string[];
  participants: string[];
  sections: NoteSection[];
  raw: string | null;
  enhanced: boolean;
}

/** One grounding citation, split into vault vs web shapes for rendering. */
export interface ParsedCitation {
  kind: "vault" | "web";
  label: string;
  url: string | null;
}

/** A persisted assistant Q&A interaction enriched with parsed citations. */
export interface AssistantQa {
  id: string;
  command: string;
  answer: string;
  citations: ParsedCitation[];
  status: string;
  sourceLabel: string | null;
  createdAt: string;
}

/**
 * The NOTE tab (default): the note IS the product, so its body comes first —
 * primary Re-summarize verb + a `⋯ More` OPAQUE overflow menu (Manage / Export
 * & save / Hi-res masters / Graph, Delete isolated last), then the rendered
 * analysis, the persisted Q&A, action items, Recipes, Ask-this-meeting chat and
 * Related. Presentational: the shell owns the meeting + all IPC handlers; this
 * panel renders inputs and emits outputs. Hosts the reused sub-components
 * (`meeting-actions` / `-recipes` / `-chat` / `related-meetings`).
 *
 * Lives in its own file so its inline styles get their own per-component
 * `anyComponentStyle` budget — the reason the giant detail component is split.
 */
@Component({
  selector: "app-note-panel",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    MarkdownComponent,
    AssistantSourcesComponent,
    MoveToMenuComponent,
    MeetingActionsComponent,
    MeetingChatComponent,
    MeetingRecipesComponent,
    RelatedMeetingsComponent,
  ],
  template: `
    <div class="note-panel">
      <!-- ANALYSIS CARD: primary verb + ⋯ More menu, then the note body. -->
      <section class="block print-keep" [class.is-resummarizing]="busy()">
        <div class="block-head">
          <button
            type="button"
            class="btn btn-primary"
            (click)="resummarize.emit()"
            [disabled]="busy() || renaming()"
          >
            Re-summarize
          </button>

          @if (provenanceLabel(); as prov) {
            <span
              class="provenance-badge"
              [attr.title]="prov.provider ? 'Provider: ' + prov.provider : null"
              [attr.aria-label]="'Generated by ' + (prov.model || prov.provider)"
            >
              <svg viewBox="0 0 16 16" width="12" height="12" fill="none" aria-hidden="true" class="provenance-icon">
                <circle cx="8" cy="8" r="6.5" stroke="currentColor" stroke-width="1.4" />
                <path d="M5.5 8.5 7.2 10.2 10.5 6" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" />
              </svg>
              @if (prov.model) {
                <span>{{ prov.model }}</span>
              }
              @if (prov.model && prov.provider) {
                <span class="provenance-sep" aria-hidden="true">·</span>
              }
              @if (prov.provider) {
                <span>{{ prov.provider }}</span>
              }
            </span>
          }

          @if (note() && !editing()) {
            <button type="button" class="btn btn-ghost edit-btn" (click)="edit.emit()">
              Edit
            </button>
          }

          <!-- ⋯ More overflow menu (OPAQUE overlay, trap T3). -->
          <div class="more" #moreAnchor>
            <button
              type="button"
              class="btn btn-ghost more-btn"
              [class.margin-when-no-badge]="!provenanceLabel() && !(note() && !editing())"
              aria-haspopup="menu"
              [attr.aria-expanded]="menuOpen()"
              (click)="toggleMenu()"
              [disabled]="busy()"
            >
              <span aria-hidden="true">⋯</span>
              <span>More</span>
            </button>
            @if (menuOpen()) {
              <div class="menu more-menu" role="menu" aria-label="More actions">
                <!-- MANAGE -->
                <div class="menu-group">
                  <span class="menu-group-label">Manage</span>
                  <button type="button" class="menu-item" role="menuitem" (click)="pick(); rename.emit()" [disabled]="busy() || renaming()">
                    Rename
                  </button>
                  <button type="button" class="menu-item" role="menuitem" (click)="move.emit()" [disabled]="busy()">
                    Move to folder…
                  </button>
                </div>

                <!-- EXPORT & SAVE -->
                @if (note()) {
                  <div class="menu-group">
                    <span class="menu-group-label">Export &amp; save</span>
                    <button type="button" class="menu-item" role="menuitem" (click)="pick(); copyMd.emit()" [disabled]="editing() || busy()">
                      {{ exportMsg() === "md-copied" ? "Copied" : "Copy Markdown" }}
                    </button>
                    <button type="button" class="menu-item" role="menuitem" (click)="pick(); saveMd.emit()" [disabled]="editing() || exporting()">
                      {{ exportMsg() === "md-saved" ? "Saved" : "Save Markdown…" }}
                    </button>
                    <button type="button" class="menu-item" role="menuitem" (click)="pick(); savePdf.emit()" [disabled]="editing()">
                      Save as PDF
                    </button>
                    <button type="button" class="menu-item" role="menuitem" (click)="pick(); exportCanvas.emit()" [disabled]="editing() || exportingCanvas()">
                      {{ exportingCanvas() ? "Exporting…" : "Export Canvas" }}
                    </button>
                    @if (hasAudio()) {
                      <button type="button" class="menu-item" role="menuitem" (click)="pick(); saveAudio.emit()" [disabled]="editing() || exporting()">
                        {{ exportMsg() === "audio-saved" ? "Saved" : "Save audio…" }}
                      </button>
                    }
                  </div>
                }

                <!-- HI-RES MASTERS -->
                @if (keepsMasters() && hasAudio()) {
                  <div class="menu-group">
                    <span class="menu-group-label">Hi-res masters</span>
                    <button type="button" class="menu-item" role="menuitem" (click)="pick(); exportMaster.emit('mic')" [disabled]="editing() || exporting()">
                      {{ exportMsg() === "mic-master-saved" ? "Saved" : "Export master (mic)…" }}
                    </button>
                    <button type="button" class="menu-item" role="menuitem" (click)="pick(); exportMaster.emit('sys')" [disabled]="editing() || exporting()">
                      {{ exportMsg() === "sys-master-saved" ? "Saved" : "Export master (system)…" }}
                    </button>
                  </div>
                }

                <!-- GRAPH -->
                @if (note()) {
                  <div class="menu-group">
                    <span class="menu-group-label">Graph</span>
                    <button type="button" class="menu-item" role="menuitem" (click)="pick(); linkGraph.emit()" [disabled]="editing() || linking()">
                      {{ linking() ? "Linking…" : "Link people & projects" }}
                    </button>
                  </div>
                }

                <!-- DELETE (danger, isolated last) -->
                <div class="menu-group">
                  <button type="button" class="menu-item menu-item-danger" role="menuitem" (click)="pick(); delete.emit()" [disabled]="busy()">
                    Delete note
                  </button>
                </div>
              </div>
            }
          </div>
        </div>

        <!-- MOVE-TO-FOLDER popover (opened from the ⋯ menu; anchored top-left). -->
        @if (moveOpen()) {
          <div class="move-pop">
            <app-move-to-menu
              [meetingId]="meetingId()"
              [currentFolderId]="folderId()"
              (moved)="moved.emit($event)"
              (close)="closeMove.emit()"
            />
          </div>
        }

        <!-- Note-tab status lines (unchanged handlers). -->
        @if (canvasMsg(); as path) {
          <div class="saved-toast canvas-toast" role="status">
            <span class="saved-toast-check" aria-hidden="true"></span>
            Canvas saved · {{ path }}
          </div>
        }
        @if (canvasError(); as err) {
          <span class="msg msg-error" role="alert">{{ err }}</span>
        }
        @if (exportError(); as err) {
          <span class="msg msg-error" role="alert">{{ err }}</span>
        }
        @if (msg()) {
          <span class="msg">{{ msg() }}</span>
        }

        <!-- Graph link result: resolved people + projects as chips + caption. -->
        @if (graphError(); as err) {
          <div class="card graph-card graph-card--error" role="alert">{{ err }}</div>
        }
        @if (graph(); as g) {
          <div class="card graph-card" role="status">
            @if (g.people.length || g.projects.length) {
              <div class="graph-groups">
                @if (g.people.length) {
                  <div class="graph-group">
                    <span class="section-label">People</span>
                    <div class="graph-pills">
                      @for (p of g.people; track p) {
                        <span class="pill tag">{{ p }}</span>
                      }
                    </div>
                  </div>
                }
                @if (g.projects.length) {
                  <div class="graph-group">
                    <span class="section-label">Projects</span>
                    <div class="graph-pills">
                      @for (pr of g.projects; track pr) {
                        <span class="pill tag graph-pill--project">{{ pr }}</span>
                      }
                    </div>
                  </div>
                }
              </div>
              <p class="graph-caption">Added to your Obsidian vault graph (People/ &amp; Projects/)</p>
            } @else {
              <p class="graph-caption">No people or projects to link yet.</p>
            }
          </div>
        }

        <!-- In-app delete confirmation (signal-driven; no window.confirm). -->
        @if (confirmingDelete()) {
          <div class="card confirm" role="alertdialog" aria-label="Delete meeting">
            <div class="confirm-text">
              <p class="confirm-title">Delete this meeting?</p>
              <p class="confirm-copy">
                This permanently removes the recording, transcript, summary and the
                note in your vault. This can’t be undone.
              </p>
              @if (deleteError(); as err) {
                <p class="confirm-error" role="alert">{{ err }}</p>
              }
            </div>
            <div class="confirm-actions">
              <button type="button" class="btn btn-ghost" (click)="cancelDelete.emit()" [disabled]="deleting()">
                Cancel
              </button>
              <button type="button" class="btn btn-danger" (click)="confirmDelete.emit()" [disabled]="deleting()">
                {{ deleting() ? "Deleting…" : "Delete" }}
              </button>
            </div>
          </div>
        }

        <!-- The note body. -->
        @if (note(); as n) {
          @if (editing()) {
            <article class="card editor">
              <textarea
                class="editor-area"
                spellcheck="false"
                autocapitalize="off"
                autocomplete="off"
                aria-label="Note markdown"
                [value]="draft()"
                [disabled]="saving()"
                (input)="draftInput.emit($any($event.target).value)"
              ></textarea>
              @if (saveError(); as err) {
                <p class="editor-error" role="alert">{{ err }}</p>
              }
              <div class="editor-foot">
                <span class="editor-hint">Markdown · saved to your vault</span>
                <div class="editor-actions">
                  <button type="button" class="btn btn-ghost" (click)="cancelEdit.emit()" [disabled]="saving()">
                    Cancel
                  </button>
                  <button type="button" class="btn btn-primary" (click)="saveNote.emit()" [disabled]="saving()">
                    {{ saving() ? "Saving…" : "Save" }}
                  </button>
                </div>
              </div>
            </article>
          } @else {
            @if (n.participants.length) {
              <div class="card meta-card">
                <span class="section-label">Participants</span>
                <div class="people">
                  @for (p of n.participants; track p) {
                    <span class="person">{{ p }}</span>
                  }
                </div>
              </div>
            }

            @if (n.sections.length) {
              @for (sec of n.sections; track sec.heading) {
                <article class="card section">
                  <h4 class="section-head">{{ sec.heading }}</h4>
                  @switch (sec.kind) {
                    @case ("actions") {
                      <ul class="checklist">
                        @for (a of sec.actions; track $index) {
                          <li class="check" [class.is-done]="a.done">
                            <span class="check-box" [class.is-done]="a.done" aria-hidden="true"></span>
                            <span class="check-text">{{ a.text }}</span>
                          </li>
                        }
                      </ul>
                    }
                    @case ("bullets") {
                      <ul class="bullets">
                        @for (b of sec.bullets; track $index) {
                          <li class="bullet">{{ b }}</li>
                        }
                      </ul>
                    }
                    @default {
                      <div class="prose">
                        @for (para of sec.paragraphs; track $index) {
                          <p>{{ para }}</p>
                        }
                      </div>
                    }
                  }
                </article>
              }
            } @else if (n.raw) {
              <article class="card section">
                <pre class="note-body">{{ n.raw }}</pre>
              </article>
            }

            @if (justSaved()) {
              <div class="saved-toast" role="status">
                <span class="saved-toast-check" aria-hidden="true"></span>
                Saved
              </div>
            }

            @if (exportedPath(); as path) {
              <div class="card saved">
                <span class="saved-icon" aria-hidden="true"></span>
                <div class="saved-body">
                  <span class="saved-label">Saved to vault</span>
                  <span class="saved-path">{{ path }}</span>
                </div>
                <button type="button" class="btn btn-ghost copy-btn" (click)="copyPath.emit()">
                  {{ pathCopied() ? "Copied" : "Copy path" }}
                </button>
              </div>
            }
          }
        } @else {
          <div class="card empty-card empty-state">
            <span class="empty-mark" aria-hidden="true"></span>
            <p class="empty-title">No analysis yet</p>
            <p class="empty">Re-summarize this meeting to generate a structured note.</p>
          </div>
        }
      </section>

      <!-- ASSISTANT Q&A (persisted in-meeting voice exchanges). -->
      @if (interactions().length) {
        <section class="block print-keep">
          <div class="block-head">
            <h3 class="section-label">🎙 Asystent — Q&amp;A</h3>
            <span class="count">{{ interactions().length }}</span>
          </div>
          <ul class="qa-list">
            @for (q of interactions(); track q.id) {
              <li class="card qa-row" [class.is-pending]="q.status === 'pending'">
                <div class="qa-heard">
                  <span class="qa-ico" aria-hidden="true">🎙</span>
                  <span class="qa-heard-text">Pytałeś: <strong>{{ q.command || "…" }}</strong></span>
                  @if (qaStatusLabel(q.status)) {
                    <span class="pill" [class]="qaStatusPillClass(q.status)">
                      <span class="pill-dot"></span>
                      {{ qaStatusLabel(q.status) }}
                    </span>
                  }
                </div>
                @if (q.answer) {
                  <app-markdown class="qa-answer" [markdown]="q.answer" compact />
                }
                @if (q.citations.length) {
                  <app-assistant-sources [citations]="q.citations" />
                }
                @if (q.sourceLabel) {
                  <span class="qa-source text-muted">{{ q.sourceLabel }}</span>
                }
              </li>
            }
          </ul>
        </section>
      }

      <!-- ACTION ITEMS (Reminders + Obsidian Tasks; hidden when none). -->
      <app-meeting-actions [meetingId]="meetingId()" />

      <!-- RECIPES / GENERATE (grounded one-tap generations over text). -->
      <section class="block">
        <div class="block-head">
          <h3 class="section-label">Recipes</h3>
        </div>
        <app-meeting-recipes [meetingId]="meetingId()" />
      </section>

      <!-- CHAT WITH THIS MEETING (grounded Q&A over the transcript). -->
      <section class="block">
        <app-meeting-chat [meetingId]="meetingId()" />
      </section>

      <!-- RELATED BY MEANING (semantic neighbors; silent when empty). -->
      <app-related-meetings [meetingId]="meetingId()" (open)="openRelated.emit($event)" />
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
      }
      .note-panel {
        display: flex;
        flex-direction: column;
        /* §5 rhythm: --space-6 between top-level sections (calm whitespace). */
        gap: var(--space-6);
        animation: rise 320ms var(--transition) both;
      }

      .block {
        display: flex;
        flex-direction: column;
        gap: var(--space-3);
      }
      .block-head {
        display: flex;
        align-items: center;
        gap: var(--space-3);
      }
      .block-head h3 {
        margin: 0;
      }
      .msg {
        color: var(--text-secondary);
        font-size: 0.85rem;
      }
      .msg-error {
        color: var(--danger);
      }

      /* ⋯ More overflow menu (anchor + opaque menu is a global primitive). */
      .more {
        position: relative;
        display: inline-flex;
        margin-left: auto;
      }
      .more-btn {
        display: inline-flex;
        align-items: center;
        gap: var(--space-2);
      }
      .more-menu {
        position: absolute;
        top: calc(100% + 8px);
        right: 0;
        z-index: 30;
        animation: rise 160ms var(--transition) both;
      }
      .move-pop {
        align-self: flex-start;
      }

      /* Model-provenance ghost chip. */
      .provenance-badge {
        display: inline-flex;
        align-items: center;
        gap: var(--space-1);
        padding: 2px var(--space-2);
        border-radius: var(--radius-pill);
        border: 1px solid var(--border-subtle);
        color: var(--text-muted);
        font-size: 0.6875rem;
        font-weight: 500;
        white-space: nowrap;
        margin-left: auto;
      }
      .provenance-badge + .edit-btn,
      .provenance-badge ~ .more {
        margin-left: var(--space-2);
      }
      .provenance-icon {
        flex: none;
        opacity: 0.7;
      }
      .provenance-sep {
        opacity: 0.5;
      }
      .edit-btn {
        margin-left: auto;
        height: 32px;
        padding: 0 var(--space-3);
        font-size: 0.8125rem;
      }
      .edit-btn + .more {
        margin-left: var(--space-2);
      }

      /* Graph link result. */
      .graph-card {
        display: flex;
        flex-direction: column;
        gap: var(--space-3);
        padding: var(--space-4) var(--space-5);
      }
      .graph-card--error {
        background: var(--danger-soft);
        color: var(--danger);
      }
      .graph-groups {
        display: flex;
        flex-wrap: wrap;
        gap: var(--space-4) var(--space-5);
      }
      .graph-group {
        display: flex;
        flex-direction: column;
        gap: var(--space-2);
        min-width: 0;
      }
      .graph-pills,
      .people {
        display: flex;
        flex-wrap: wrap;
        gap: var(--space-2);
      }
      .graph-pill--project {
        background: var(--success-soft);
        color: var(--success);
      }
      .graph-caption {
        margin: 0;
        color: var(--text-muted);
        font-size: 0.8125rem;
      }
      .tag {
        height: 24px;
        padding: var(--space-1) var(--space-3);
        background: var(--accent-soft);
        border-color: transparent;
        color: var(--accent-hover);
        font-size: 0.75rem;
        font-weight: 600;
      }

      /* Delete confirmation. */
      .confirm {
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        justify-content: space-between;
        gap: var(--space-4);
        border-color: rgba(255, 107, 107, 0.3);
        animation: rise 240ms var(--transition) both;
      }
      .confirm-text {
        min-width: 0;
        flex: 1 1 20rem;
      }
      .confirm-title {
        margin: 0 0 var(--space-1);
        color: var(--text-primary);
        font-weight: 600;
      }
      .confirm-copy {
        margin: 0;
        color: var(--text-secondary);
        font-size: 0.875rem;
        line-height: 1.55;
      }
      .confirm-error {
        margin: var(--space-2) 0 0;
        color: var(--danger);
        font-size: 0.85rem;
      }
      .confirm-actions,
      .editor-actions {
        display: flex;
        align-items: center;
        gap: var(--space-2);
        margin-left: auto;
      }

      /* Note body: participants + sections. */
      .meta-card {
        display: flex;
        flex-direction: column;
        gap: var(--space-3);
        padding: var(--space-4) var(--space-5);
      }
      .person {
        display: inline-flex;
        align-items: center;
        padding: var(--space-1) var(--space-3);
        border-radius: var(--radius-pill);
        background: var(--surface-input);
        border: 1px solid var(--border);
        color: var(--text-secondary);
        font-size: 0.8125rem;
        font-weight: 550;
      }
      .section {
        padding: var(--space-5);
        transition:
          transform var(--transition),
          border-color var(--transition);
      }
      .section:hover {
        border-color: var(--border-strong);
      }
      .prose p {
        margin: 0 0 var(--space-3);
        color: var(--text-secondary);
        line-height: 1.7;
        max-width: 68ch;
      }
      .prose p:last-child {
        margin-bottom: 0;
      }
      .bullets {
        list-style: none;
        margin: 0;
        padding: 0;
        display: flex;
        flex-direction: column;
        gap: var(--space-2);
      }
      .bullet {
        position: relative;
        padding-left: var(--space-5);
        color: var(--text-secondary);
        line-height: 1.6;
      }
      .bullet::before {
        content: "";
        position: absolute;
        left: 4px;
        top: 0.62em;
        width: 6px;
        height: 6px;
        border-radius: 50%;
        background: var(--accent);
      }
      .checklist {
        list-style: none;
        margin: 0;
        padding: 0;
        display: flex;
        flex-direction: column;
        gap: var(--space-3);
      }
      .check {
        display: flex;
        align-items: flex-start;
        gap: var(--space-3);
        line-height: 1.5;
      }
      .check-box {
        flex: none;
        position: relative;
        width: 20px;
        height: 20px;
        margin-top: 0.05em;
        border: 1px solid var(--border-strong);
        border-radius: var(--radius-sm);
        background: var(--surface-input);
      }
      .check-box.is-done {
        background: var(--accent-gradient);
        border-color: transparent;
      }
      .check-box.is-done::after {
        content: "";
        position: absolute;
        left: 6px;
        top: 2px;
        width: 5px;
        height: 10px;
        border: solid var(--text-on-accent);
        border-width: 0 2px 2px 0;
        transform: rotate(45deg);
      }
      .check-text {
        color: var(--text-secondary);
        min-width: 0;
      }
      .check.is-done .check-text {
        color: var(--text-muted);
        text-decoration: line-through;
        text-decoration-color: var(--text-muted);
      }
      .note-body {
        margin: 0;
        white-space: pre-wrap;
        background: var(--surface-input);
        border: 1px solid var(--border-subtle);
        color: var(--text-secondary);
        padding: var(--space-4);
        border-radius: var(--radius-md);
        max-height: 420px;
        overflow: auto;
        font-size: 0.9rem;
        line-height: 1.7;
      }

      /* Assistant Q&A section. */
      .qa-list {
        list-style: none;
        margin: 0;
        padding: 0;
        display: flex;
        flex-direction: column;
        gap: var(--space-3);
      }
      .qa-row {
        display: flex;
        flex-direction: column;
        gap: var(--space-2);
        padding: var(--space-3) var(--space-4);
      }
      .qa-heard {
        display: flex;
        align-items: center;
        flex-wrap: wrap;
        gap: var(--space-2);
      }
      .qa-heard-text {
        color: var(--text-secondary);
        font-size: 0.875rem;
      }
      .qa-heard-text strong {
        color: var(--text-primary);
        font-weight: 600;
      }
      .qa-heard .pill {
        margin-left: auto;
      }
      .qa-answer {
        display: block;
        font-size: 0.9rem;
      }
      .qa-source {
        font-size: 0.72rem;
        text-transform: uppercase;
        letter-spacing: 0.03em;
      }

      /* Saved-to-vault line + toasts. */
      .saved {
        display: flex;
        align-items: center;
        gap: var(--space-3);
        padding: var(--space-3) var(--space-4);
      }
      .saved-icon {
        flex: none;
        width: 8px;
        height: 8px;
        border-radius: 50%;
        background: var(--success);
        box-shadow: 0 0 0 4px var(--success-soft);
      }
      .saved-body {
        display: flex;
        flex-direction: column;
        gap: 2px;
        min-width: 0;
        flex: 1 1 auto;
      }
      .saved-label {
        color: var(--text-secondary);
        font-size: 0.8125rem;
        font-weight: 600;
      }
      .saved-path {
        color: var(--text-muted);
        font-family: var(--font-mono);
        font-size: 0.75rem;
        word-break: break-all;
      }
      .copy-btn {
        flex: none;
        height: 32px;
        padding: 0 var(--space-3);
        font-size: 0.8125rem;
      }
      .saved-toast {
        display: inline-flex;
        align-items: center;
        gap: var(--space-2);
        align-self: flex-start;
        padding: var(--space-1) var(--space-3);
        min-height: 28px;
        border-radius: var(--radius-pill);
        background: var(--success-soft);
        color: var(--success);
        font-size: 0.8125rem;
        font-weight: 600;
        animation: rise 280ms var(--transition) both;
      }
      .canvas-toast {
        word-break: break-all;
      }
      .saved-toast-check {
        position: relative;
        width: 14px;
        height: 14px;
        flex: none;
      }
      .saved-toast-check::after {
        content: "";
        position: absolute;
        left: 4px;
        top: 0;
        width: 4px;
        height: 9px;
        border: solid currentColor;
        border-width: 0 2px 2px 0;
        transform: rotate(45deg);
      }

      /* In-app note editor. */
      .editor {
        display: flex;
        flex-direction: column;
        gap: var(--space-3);
        padding: var(--space-4);
      }
      .editor-area {
        width: 100%;
        min-height: 360px;
        flex: 1 1 auto;
        padding: var(--space-4);
        border: 1px solid var(--border-subtle);
        border-radius: var(--radius-md);
        background: var(--surface-input);
        color: var(--text-primary);
        font-family: var(--font-mono);
        font-size: 0.875rem;
        font-variant-numeric: tabular-nums;
        line-height: 1.7;
        resize: vertical;
        tab-size: 2;
      }
      .editor-error {
        margin: 0;
        padding: var(--space-2) var(--space-3);
        border: 1px solid rgba(255, 107, 107, 0.3);
        border-radius: var(--radius-sm);
        background: var(--danger-soft);
        color: var(--text-primary);
        font-size: 0.85rem;
      }
      .editor-foot {
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        justify-content: space-between;
        gap: var(--space-3);
      }
      .editor-hint {
        margin: 0;
        color: var(--text-muted);
        font-size: 0.8125rem;
      }
      .empty-card {
        padding: var(--space-5);
      }

      .is-resummarizing {
        opacity: 0.55;
        pointer-events: none;
        transition: opacity var(--transition);
      }

      @media (prefers-reduced-motion: reduce) {
        .note-panel,
        .more-menu,
        .confirm,
        .saved-toast {
          animation: none;
        }
      }

      @media print {
        .block-head .btn,
        .block-head .more,
        .block-head .edit-btn,
        .block .saved,
        .block .saved-toast {
          display: none !important;
        }
      }
    `,
  ],
})
export class NotePanelComponent {
  // --- Identity / meeting inputs ------------------------------------------
  readonly meetingId = input.required<string>();
  readonly folderId = input<string | null>(null);
  /** The parsed note body (null when there is no note / masked). */
  readonly note = input<ParsedNote | null>(null);
  /** The persisted in-meeting assistant Q&A. */
  readonly interactions = input<AssistantQa[]>([]);
  /** The vault export path from the note DTO (Saved-to-vault line). */
  readonly exportedPath = input<string | null>(null);
  /** Model provenance for the ghost badge (null → hidden). */
  readonly provenanceLabel = input<{ model: string; provider: string } | null>(null);

  // --- Busy / capability flags (mirror the shell) -------------------------
  readonly busy = input(false);
  readonly renaming = input(false);
  readonly editing = input(false);
  readonly saving = input(false);
  readonly exporting = input(false);
  readonly exportingCanvas = input(false);
  readonly linking = input(false);
  readonly keepsMasters = input(false);
  readonly hasAudio = input(false);
  readonly moveOpen = input(false);

  // --- Transient status text ----------------------------------------------
  readonly msg = input("");
  readonly exportMsg = input("");
  readonly exportError = input("");
  readonly canvasMsg = input("");
  readonly canvasError = input("");
  readonly graph = input<GraphPayload | null>(null);
  readonly graphError = input("");
  readonly justSaved = input(false);
  readonly pathCopied = input(false);

  // --- Editor / delete state ----------------------------------------------
  readonly draft = input("");
  readonly saveError = input("");
  readonly confirmingDelete = input(false);
  readonly deleting = input(false);
  readonly deleteError = input("");

  // --- Outputs back to the shell (which owns the IPC + writable state) -----
  readonly resummarize = output<void>();
  readonly rename = output<void>();
  readonly move = output<void>();
  readonly moved = output<string | null>();
  readonly closeMove = output<void>();
  readonly delete = output<void>();
  readonly cancelDelete = output<void>();
  readonly confirmDelete = output<void>();
  readonly copyMd = output<void>();
  readonly saveMd = output<void>();
  readonly savePdf = output<void>();
  readonly exportCanvas = output<void>();
  readonly saveAudio = output<void>();
  readonly exportMaster = output<"mic" | "sys">();
  readonly linkGraph = output<void>();
  readonly edit = output<void>();
  readonly cancelEdit = output<void>();
  readonly saveNote = output<void>();
  readonly draftInput = output<string>();
  readonly copyPath = output<void>();
  readonly openRelated = output<string>();

  // --- ⋯ More overlay menu (local presentational open/close) --------------
  private readonly moreAnchor =
    viewChild<ElementRef<HTMLElement>>("moreAnchor");
  readonly menuOpen = signal(false);

  toggleMenu(): void {
    this.menuOpen.update((v) => !v);
  }

  /** Close the menu after an item fires (the action itself is an output). */
  pick(): void {
    this.menuOpen.set(false);
  }

  /** Whether the menu should offset the ⋯ trigger when no badge precedes it. */
  readonly hasTrailingBadge = computed(
    () => this.provenanceLabel() !== null,
  );

  /** Map an interaction status to a global `.pill` variant. */
  qaStatusPillClass(status: string): string {
    switch (status) {
      case "ok":
        return "is-success";
      case "needs_consent":
        return "is-warning";
      case "unavailable":
      case "unrecognized":
        return "is-accent";
      case "nothing_heard":
        return "";
      default:
        return "is-danger";
    }
  }

  /** Short human label for the status pill. */
  qaStatusLabel(status: string): string {
    switch (status) {
      case "ok":
        return "Odpowiedziano";
      case "needs_consent":
        return "Wymaga zgody";
      case "unavailable":
        return "Niedostępne";
      case "unrecognized":
        return "Nierozpoznane";
      case "nothing_heard":
        return "Nic nie usłyszano";
      case "error":
        return "Błąd";
      default:
        return status;
    }
  }

  /** Suppress unused-viewChild lint while keeping the anchor ref available. */
  protected anchorEl(): HTMLElement | null {
    return this.moreAnchor()?.nativeElement ?? null;
  }
}
